# Site settings
title: vectorscores
email: john@johnteskemusic.com
description: >
    A series of new compositions built on the web.
baseurl: "/vectorscores"
url: "http://vectorscores.org"
twitter_username: johnteske
github_username:  johnteske/vectorscores
website: http://johnteskemusic.com

# Build settings
safe: true
markdown: kramdown
sass:
    style: compressed

# Compression settings
compress_html:
    clippings: all
    comments: all #["<!-- ", " -->"]
    #endings: all
    ignore:
        envs: [debug]
    #blanklines: false
    #profile: true
    #startings: [html, head, body]
