# Site settings
title: vectorscores
email: john@johnteskemusic.com
description: >
    A new series of dynamic compositions.
baseurl: "/vectorscores"
url: "http://vectorscores.org"
twitter_username: johnteske
github_username:  johnteske/vectorscores
website: http://johnteskemusic.com

# Build settings
safe: true
markdown: kramdown
sass:
    style: compressed
include: ["_pages"]
exclude: ["bin", "docs/README.md"]

# Compression settings
compress_html:
    clippings: all
    comments: all #["<!-- ", " -->"]
    #endings: all
    ignore:
        envs: [debug]
    #blanklines: false
    #profile: true
    #startings: [html, head, body]

defaults:
    # Compress modules by default (and allow linting by excluding frontmatter in each file)
    -
        scope:
            path: "js/vs/modules"
        values:
            layout: "compress-js"
