# Site settings
title: vectorscor.es
email: john@johnteskemusic.com
description: >
    A series of new compositions built on the web.
baseurl: "/vectorscores" # the subpath of your site, e.g. /blog
url: "http://vectorscor.es" # the base hostname & protocol for your site
twitter_username: johnteske
github_username:  johnteske/vectorscores
website: http://johnteskemusic.com

# Build settings
safe: true
markdown: kramdown
sass:
    style: compressed
